# Generated by Django 4.2.5 on 2023-10-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='pashinator', max_length=100),
            preserve_default=False,
        ),
    ]
