# Generated by Django 4.2.4 on 2023-08-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/None/No-img.jpg', upload_to='images/'),
        ),
    ]
